---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  namespace: myntra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
      - name: myntra
        image: vaibhavbankar/myntra:13
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: myntra-service
  namespace : myntra
spec:
  selector:
    app: myntra
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
    NodePort: 32002
  type: NodePort
